log-level: "info"
db:
  connection-string: "postgres://wwmap:WWMAP_POSTGRES_PASSWORD@localhost:5432/wwmap?sslmode=require"
  max-open-conn: 5
  max-iddle-conn: 5
  max-conn-lifetime: "5m"
clusterization:
  barrier_ratio: 2
  min_dist_ratio: 50
  single_point_cluster_max_zoom: 8
  min_clustered_points_ratio: 0.5
  max_clusters_per_river: 1


notifications:
  email_recipients:
    - "and.hom@gmail.com"
  email_sender: "and.hom@gmail.com"
  reporting_email_subject: "Есть новые сообщения о неточностях"
  import_export_email_subject: "Отчёт об импорте-экспорте каталога"

api:
  bind_to: ":7007"
tile-cache:
  bind_to: ":7008"
  base_dir: "/var/lib/wwmap/t-cache"
  types:
    osm:
      url:
        - "http://a.tile.openstreetmap.org/{{.z}}/{{.x}}/{{.y}}.png"
        - "http://b.tile.openstreetmap.org/{{.z}}/{{.x}}/{{.y}}.png"
        - "http://c.tile.openstreetmap.org/{{.z}}/{{.x}}/{{.y}}.png"
    ggc:
      url:
        - "https://maps.melda.ru/pub/ggc/{{if lt .z 12}}2km.png{{else}}{{if lt .z 13}}1km.png{{else}}{{if lt .z 14}}500m.png{{else}}250m.png{{end}}{{end}}{{end}}/z{{sum .z 1}}/{{div .x 1024}}/x{{.x}}/{{div .y 1024}}/y{{.y}}.png"
      #        - "http://91.237.82.95:8088/pub/ggc/{{if lt .z 13}}2km.png{{else}}{{if lt .z 14}}1km.png{{else}}{{if lt .z 15}}500m.png{{else}}250m.png{{end}}{{end}}{{end}}/z{{sum .z 1}}/{{div .x 1024}}/x{{.x}}/{{div .y 1024}}/y{{.y}}.png"
      max_parallel_requests: 20
      headers:
        User-Agent: "Opera/9.80 (Windows NT 6.1) Presto/2.12.388 Version/12.16"
        Referer: "http://kosmosnimki.ru/"
        Accept: "text/html, application/xml;q=0.9, application/xhtml+xml, image/png, image/webp, image/jpeg, image/gif, image/x-xbitmap, */*;q=0.1"
        Accept-Language: "ru-RU,ru;q=0.9,en;q=0.8"
    marshruty-ru:
      url:
        - "http://maps.marshruty.ru/ml.ashx?al=1&x={{.x}}&y={{.y}}&z={{.z}}"
    topo-mapper:
      url:
        - "http://144.76.234.108/cgi-bin/tapp/tilecache.py/1.0.0/topomapper_v2/{{.z}}/{{.x}}/{{.y}}"
cron:
  bind_to: ":7009"
  read_timeout: 5s
  write_timeout: 5s
  log_dir: "/var/lib/wwmap/cron/logs/"
content:
  resource_base: "http://wwmap.ru"
img-storage:
  full:
    dir: "/var/lib/wwmap/backend/images/full"
    url-base: "http://localhost:7007/spot/0/img/%d"
  preview:
    dir: "/var/lib/wwmap/backend/images/preview"
    url-base: "http://localhost:7007/spot/0/img/%d/preview"
river-passport-pdf-storage:
  dir: "/var/lib/wwmap/backend/river-passport"
  url-base: "http://localhost:7007/river/%d/pdf"
  suffix: "pdf"
river-passport-html-storage:
  dir: "/var/lib/wwmap/backend/river-passport"
  url-base: "http://localhost:7007/river/%d/html"
  suffix: "htm"


backup:
  email: "info@wwmap.ru"
  password: ""

sync:
  login: "wwmap"
  password: ""
  root-page-id: 1739
  min-delta-between-requests: "1s"