db-connection-string: "postgres://wwmap:$WWMAP_POSTGRES_PASSWORD@localhost:5432/wwmap?sslmode=require"
clusterization:
  barrier_ratio: 0.002
  min_dist_ratio: 0.1
  single_point_cluster_max_zoom: 6


notifications:
  email_recipients:
    - "and.hom@gmail.com"
  email_sender: "and.hom@gmail.com"
  email_subject: "Есть новые сообщения о неточностях"
api:
  bind_to: ":7007"
tile-cache:
  bind_to: ":7008"
  base_dir: "/var/lib/wwmap/t-cache"
  types:
    osm:
      - "http://a.tile.openstreetmap.org/{{.z}}/{{.x}}/{{.y}}.png"
      - "http://b.tile.openstreetmap.org/{{.z}}/{{.x}}/{{.y}}.png"
      - "http://c.tile.openstreetmap.org/{{.z}}/{{.x}}/{{.y}}.png"
    ggc:
      - "http://maps.melda.ru/pub/ggc/{{if lt .z 12}}2km.png{{else}}{{if lt .z 13}}1km.png{{else}}250m.png{{end}}{{end}}/z{{sum .z 1}}/{{div .x 1024}}/x{{.x}}/{{div .y 1024}}/y{{.y}}.png"
    marshruty-ru:
      - "http://maps.marshruty.ru/ml.ashx?al=1&x={{.x}}&y={{.y}}&z={{.z}}"
content:
  resource_base: "http://wwmap.ru"

backup:
  email: "info@wwmap.ru"
  password: ""
