db-connection-string: "postgres://wwmap:$WWMAP_POSTGRES_PASSWORD@localhost:5432/wwmap?sslmode=require"
clusterization:
  barrier_ratio: 0.002
  min_dist_ratio: 0.1
  single_point_cluster_max_zoom: 6


notifications:
  email_recipients:
    - "and.hom@gmail.com"
  email_sender: "and.hom@gmail.com"
  email_subject: "Есть новые сообщения о неточностях"
api:
  bind_to: ":7007"
tile-cache:
  bind_to: ":7008"
  base_dir: "/var/lib/wwmap/t-cache"
  types:
    osm:
      - "http://a.tile.openstreetmap.org/[[z]]/[[x]]/[[y]].png"
      - "http://b.tile.openstreetmap.org/[[z]]/[[x]]/[[y]].png"
      - "http://c.tile.openstreetmap.org/[[z]]/[[x]]/[[y]].png"
content:
  resource_base: "http://wwmap.ru"

backup:
  email: "info@wwmap.ru"
  password: ""
